### ISSUE TITLE
Not parsing included nested sections

### ISSUE THREAD

**Issue by agarwalrohit2503** [infinum/flutter-plugins-japx#26]
[json.txt](https://github.com/infinum/flutter-plugins-japx/files/12763139/json.txt)

Have added the json file
Please look into this

**Comment by agarwalrohit2503** [comment]
[json.txt](https://github.com/infinum/flutter-plugins-japx/files/12763139/json.txt)

Have added the json file 
Please look into this

**Comment by zenled** [comment]
Closing, this is a duplicate of #27
